### ISSUE TITLE
怎么编译呢 我用C++17编译 一大堆报错

### ISSUE THREAD

**Issue by yk133** [drizmiz/GameOfTheAmazons#1]
怎么编译或者需要什么环境?
Linux上可以吗?
没下载VS

**Comment by drizmiz** [comment]
emmm因为我本地是用msvc编译的，所以我把__GNUC__当成_BOTZONE_ONLINE用了（捂脸逃），已经修复了此问题，现在的版本经g++ 8.1.0编译通过
